cmake_minimum_required(VERSION 3.22.1)
project(seafrogs_hdr LANGUAGES CXX)
add_library(hdr_kernel STATIC IMPORTED)
set_target_properties(hdr_kernel PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_SOURCE_DIR}/generated/${ANDROID_ABI}/seafrogs_hdr.a")
add_library(seafrogs_hdr SHARED hdr_jni.cpp)
target_compile_features(seafrogs_hdr PRIVATE cxx_std_17)
target_include_directories(seafrogs_hdr PRIVATE "generated/${ANDROID_ABI}")
target_link_libraries(seafrogs_hdr PRIVATE hdr_kernel jnigraphics log)
target_link_options(seafrogs_hdr PRIVATE "-Wl,-z,max-page-size=16384")
